### PR TITLE
Make ContactPoints configurable

### PR DESCRIPTION
**Pull request by jmoney**
@stuartgunter what do you think of making contactPoints into a factory instead of a static array in the yaml.  I allowed for a static array solution to be available by default but allows other applications to register their own types for how they want to inject the contact points(saying using service discovery in consul or zookeeper or etcd).

### CODE REVIEW

**Comment by stuartgunter** [comment]
Do you have a real production use case that requires this? I worry that it's a bit hypothetical. For example, if someone was using discovery to connect to Cassandra then they'd need a lot more than just `contactPoints` provided to them.

In general, I see this as a way to support Dropwizard-style configuration for Cassandra, whereas a solution that supported Consul / Zookeeper, etc. would no longer be specific to Dropwizard and should in theory work in other frameworks.

**Comment by jmoney8080** [comment]
Yes, I would like to use consul for discovering nodes to connect to at startup so we do have a prod use case.

What other information would you need other than contact points? For the cluster perspective, all it needs is an initial seed list and that's all I'm suggesting we make configurable.

**Comment by stuartgunter** [comment]
> What other information would you need other than contact points? For the cluster perspective, all it needs is an initial seed list and that's all I'm suggesting we make configurable.

I'm not sure about your specific use case, but the contact points are probably the minimal set of info needed. I'd imagine many other configuration values would potentially be sourced from service discovery (e.g. `port`).

I'm unsure whether this fits with the purpose of this library, which has so far been quite narrowly defined as a way to define Cassandra cluster via Dropwizard YAML alone.

**Comment by stuartgunter** [comment]
I've been thinking a bit more about this and I wonder whether a better solution would be to make Dropwizard a bit more flexible in how it sources configuration. It seems this is somewhat hard-coded, but I haven't really trawled through in much detail yet.

See here for one of the places where DW handled configuration:
https://github.com/dropwizard/dropwizard/blob/release/1.0.x/dropwizard-core/src/main/java/io/dropwizard/setup/Bootstrap.java#L51

My worry with doing the Consul-style parsing _within_ `dropwizard-cassandra` is that it will make the config file much harder to read & write and would increase duplication - and it'll only solve it for this one thing. If a project uses Consul, etc. it's likely to need it for more than just Cassandra - so it'd be better to have some kind of config pre-processor that can deal with substitutions from whatever service-discovery product you're using.

Conceptually, I wonder whether it'd be preferable to have a config file something like:

```yaml
cassandra:
  contactPoints: ${discovery.cassandra.contactPoints}

mailgun:
  url: ${discovery.mailgun.url}
```

And then configure a pre-processor that substitutes all `${}` values from service discovery?

**Pull request closed without merging**
